.github/workflows/gitflow-prod-release.yml
.github/workflows/gitflow-release.yml

Updates references from DEMO to STAGING in GH (GitHub) action pipeline variables for consistency with new naming conventions.
Updates references from DEMO to STAGING in GH action pipeline variables for consistency with new naming conventions.
To be tested by next release through GH actions.

feature(NON-REQ): update gh actions staging variable name

---

frontend/src/components/CustomForms/FormInstances/AddFormInstance.tsx
frontend/src/components/CustomForms/FormTemplates/CustomLabelField.tsx
frontend/src/components/CustomForms/FormTemplates/FormBuilder.tsx
frontend/src/components/CustomForms/FormTemplates/FormPreview.tsx
frontend/src/components/CustomForms/FormTemplates/SortableFieldRow.tsx
frontend/src/components/CustomForms/FormTemplates/types.ts
frontend/src/components/CustomForms/utils.ts
frontend/src/pages/Forms/FormInstances.tsx
frontend/src/pages/Home.tsx

- Adds concept of non-input labels to forms
- Restricts character length of input labels
- Amends styling of submitted forms so that text appears underneath header
- Adds concept of non-input labels to forms
- Restricts character length of input labels
- Amends styling of submitted forms so that text appears underneath header
Tested e2e with adding labels and inputting form data into form with labels

feat([DPAV-250]) Add Form Labels + Amend Styling

---

CHANGELOG.md
frontend/src/components/AddEntry/Header/Tabs.tsx
frontend/src/components/CustomForms/FormInstances/AddFormInstance.tsx
frontend/src/components/CustomForms/FormTemplates/CustomLabelField.tsx
frontend/src/components/CustomForms/FormTemplates/SortableFieldRow.tsx
frontend/src/pages/Forms/FormInstances.tsx
frontend/src/pages/Tasks.tsx

Resolves some of the minor styling issues in LISA, specifically around Tasks and Forms
- Form Instance wrapping has been added for large text entries
- Alignment of Task data has been modified so it is more in-line and doesn't change alignment with dynamic screen width
- Resolved form submission with required field not populated clearing all data
- Moved log entry tabs back to right hand side of screen
- Form tab is shown as active when user first navigates to add log entry screen
Tested e2e and validated all scenarios along with regression.

fix([NON-REQ]) Further amendments to Task and Forms styling

---

CHANGELOG.md
deployment/k8s/backend/overlays/dft/prod/kustomization.yaml
deployment/k8s/backend/overlays/dft/prod/patches/allow-ingress.yaml
deployment/k8s/backend/overlays/dft/prod/patches/service-account.yaml
deployment/k8s/backend/overlays/dft/prod/patches/vaultStaticSecret.yaml
deployment/k8s/backend/overlays/dft/staging/kustomization.yaml
deployment/k8s/backend/overlays/dft/staging/patches/allow-ingress.yaml
deployment/k8s/backend/overlays/dft/staging/patches/service-account.yaml
deployment/k8s/backend/overlays/dft/staging/patches/vaultStaticSecret.yaml

Deploys Lisa-DFT to Staging environment
Deploys Lisa-DFT to Staging environment
Needs deploying

feat([DPAV-765]) Deploy LISA-DFT to Staging

---

CHANGELOG.md
deployment/k8s/bootstrap/overlays/dft/prod/kustomization.yaml
deployment/k8s/bootstrap/overlays/dft/prod/patches/gateway.yaml
deployment/k8s/bootstrap/overlays/dft/prod/patches/request-authentication.yaml
deployment/k8s/bootstrap/overlays/dft/prod/patches/virtualService.yaml
deployment/k8s/bootstrap/overlays/dft/staging/kustomization.yaml
deployment/k8s/bootstrap/overlays/dft/staging/patches/gateway.yaml
deployment/k8s/bootstrap/overlays/dft/staging/patches/request-authentication.yaml
deployment/k8s/bootstrap/overlays/dft/staging/patches/virtualService.yaml
deployment/k8s/transparent-proxy/overlays/dft/prod/kustomization.yaml
deployment/k8s/transparent-proxy/overlays/dft/prod/patches/allow-ingress-to-lisa-transparent-proxy.yaml
deployment/k8s/transparent-proxy/overlays/dft/prod/patches/service-account.yaml
deployment/k8s/transparent-proxy/overlays/dft/prod/patches/vaultStaticSecret.yaml
deployment/k8s/transparent-proxy/overlays/dft/staging/kustomization.yaml
deployment/k8s/transparent-proxy/overlays/dft/staging/patches/allow-ingress-to-lisa-transparent-proxy.yaml
deployment/k8s/transparent-proxy/overlays/dft/staging/patches/service-account.yaml
deployment/k8s/transparent-proxy/overlays/dft/staging/patches/vaultStaticSecret.yaml
deployment/k8s/webapp/overlays/dft/prod/kustomization.yaml
deployment/k8s/webapp/overlays/dft/prod/patches/allow-ingress-authorization-policy.yaml
deployment/k8s/webapp/overlays/dft/prod/patches/service-account.yaml
deployment/k8s/webapp/overlays/dft/staging/kustomization.yaml
deployment/k8s/webapp/overlays/dft/staging/patches/allow-ingress-authorization-policy.yaml
deployment/k8s/webapp/overlays/dft/staging/patches/service-account.yaml

Adds in missing LISA scripts for DFT Staging/Prod deployment
Adds in missing LISA scripts for DFT Staging/Prod deployment
Needs deploying

feat([DPAV-765]) Add in missing LISA DFT deployment scripts

---

deployment/k8s/bootstrap/overlays/dft/prod/kustomization.yaml
deployment/k8s/bootstrap/overlays/dft/staging/kustomization.yaml
deployment/k8s/transparent-proxy/overlays/dft/prod/kustomization.yaml
deployment/k8s/transparent-proxy/overlays/dft/staging/kustomization.yaml
deployment/k8s/webapp/overlays/dft/prod/kustomization.yaml
deployment/k8s/webapp/overlays/dft/staging/kustomization.yaml

Corrects base paths for DFT overlays
Corrects base paths for DFT overlays
Needs deploying

fix([DPAV-765]) Modify base paths for DFT

---

deployment/k8s/backend/overlays/dft/dev/kustomization.yaml
deployment/k8s/backend/overlays/dft/dev/patches/vaultAuth.yaml
deployment/k8s/backend/overlays/dft/prod/kustomization.yaml
deployment/k8s/backend/overlays/dft/prod/patches/vaultAuth.yaml
deployment/k8s/backend/overlays/dft/staging/kustomization.yaml
deployment/k8s/backend/overlays/dft/staging/patches/vaultAuth.yaml
deployment/k8s/transparent-proxy/overlays/dft/dev/kustomization.yaml
deployment/k8s/transparent-proxy/overlays/dft/dev/patches/vaultAuth.yaml
deployment/k8s/transparent-proxy/overlays/dft/prod/kustomization.yaml
deployment/k8s/transparent-proxy/overlays/dft/prod/patches/vaultAuth.yaml
deployment/k8s/transparent-proxy/overlays/dft/staging/kustomization.yaml
deployment/k8s/transparent-proxy/overlays/dft/staging/patches/vaultAuth.yaml

Corrects vault auth for LISA DFT
Corrects vault auth for LISA DFT
Needs deploying, infrastructure already corrected

fix([DPAV-765]) Add correct roles for vault auth to DFT

---

CHANGELOG.md
deployment/k8s/backend/overlays/dft/dev/params.env
deployment/k8s/backend/overlays/dft/dev/patches/allow-ingress.yaml
deployment/k8s/backend/overlays/dft/prod/params.env
deployment/k8s/backend/overlays/dft/prod/patches/allow-ingress.yaml
deployment/k8s/backend/overlays/dft/staging/params.env
deployment/k8s/backend/overlays/dft/staging/patches/allow-ingress.yaml
deployment/k8s/transparent-proxy/overlays/dft/dev/patches/allow-ingress-to-lisa-transparent-proxy.yaml
deployment/k8s/transparent-proxy/overlays/dft/prod/patches/allow-ingress-to-lisa-transparent-proxy.yaml
deployment/k8s/transparent-proxy/overlays/dft/staging/patches/allow-ingress-to-lisa-transparent-proxy.yaml
deployment/k8s/webapp/overlays/dft/dev/patches/allow-ingress-authorization-policy.yaml
deployment/k8s/webapp/overlays/dft/prod/patches/allow-ingress-authorization-policy.yaml
deployment/k8s/webapp/overlays/dft/staging/patches/allow-ingress-authorization-policy.yaml

Amends access to L!SA (Hantsar) from lisa_dft_access group membership to lisa_hantsar_access group membership
Amends access to L!SA (Hantsar) from lisa_dft_access group membership to lisa_hantsar_access group membership
Needs to be deployed

feat([DPAV-904]) Update lisa_dft_access group to lisa_hantsar_access

---

CHANGELOG.md
deployment/k8s/backend/overlays/iwc/dev/kustomization.yaml
deployment/k8s/backend/overlays/iwc/dev/params.env
deployment/k8s/backend/overlays/iwc/dev/patches/allow-ingress.yaml
deployment/k8s/backend/overlays/iwc/dev/patches/service-account.yaml
deployment/k8s/backend/overlays/iwc/dev/patches/vaultAuth.yaml
deployment/k8s/backend/overlays/iwc/dev/patches/vaultStaticSecret.yaml
deployment/k8s/backend/overlays/iwc/prod/kustomization.yaml
deployment/k8s/backend/overlays/iwc/prod/params.env
deployment/k8s/backend/overlays/iwc/prod/patches/allow-ingress.yaml
deployment/k8s/backend/overlays/iwc/prod/patches/service-account.yaml
deployment/k8s/backend/overlays/iwc/prod/patches/vaultAuth.yaml
deployment/k8s/backend/overlays/iwc/prod/patches/vaultStaticSecret.yaml
deployment/k8s/backend/overlays/iwc/staging/kustomization.yaml
deployment/k8s/backend/overlays/iwc/staging/params.env
deployment/k8s/backend/overlays/iwc/staging/patches/allow-ingress.yaml
deployment/k8s/backend/overlays/iwc/staging/patches/service-account.yaml
deployment/k8s/backend/overlays/iwc/staging/patches/vaultAuth.yaml
deployment/k8s/backend/overlays/iwc/staging/patches/vaultStaticSecret.yaml

Adds deployment resources for a new L!SA instance across environments, with access controls and routing.
Adds deployment resources for a new L!SA instance across environments, with access controls and routing. Updates made are scoped exclusively to deployment resources.
To be tested in remote deployment environment.

feature(DPAV-970): Add resources for new L!SA instance across environments

---

deployment/k8s/backend/base/istio/allow-ingress-authorization-policy.yaml
deployment/k8s/bootstrap/overlays/dft/staging/patches/virtualService.yaml
deployment/k8s/bootstrap/overlays/iwc/staging/patches/virtualService.yaml
deployment/k8s/bootstrap/overlays/staging/patches/virtualService.yaml

CSP adjustments to allow for API invocation of sign out endpoint in staging environment for dedicated LISA instances.
CSP adjustments to allow for API invocation of sign out endpoint in staging environment for dedicated LISA instances.
To be tested in remote deployment environment.

fix(DPAV-970): CSP fixes for staging

---

backend/src/services/logEntry/utils/mentions/utils.ts
deployment/sag/docker-compose.yaml
frontend/package.json

[DPAV-1155]
- Added a check to see if the parsed JSON content is not empty before processing to find file mentions from the log entry content.
Tested locally and is working e2e.

bugfix(dpav-1155): added empty json content check to reconcile file mentions

---

frontend/src/hooks/useLogEntriesUpdates.tsx

https://ndtp.atlassian.net/browse/DPAV-1149

fix(DPAV-1149): show log entries in log not just via toast click

---

frontend/src/pages/Tasks.tsx

https://ndtp.atlassian.net/browse/DPAV-1253

feat(DPAV-1253): prevent setting a past status on a task

---

backend/eslint.config.mjs
backend/src/services/notifications/index.ts
backend/src/services/notifications/utils.ts
common/Notification.ts
frontend/src/components/NotificationsMenu/NotificationContent.tsx
frontend/src/components/NotificationsMenu/NotificationItem.tsx
frontend/src/components/NotificationsMenu/handlers.tsx
frontend/src/hooks/__tests__/notification.mock.ts
frontend/src/utils/Format/date.ts

Data changes are needed to support the new way of displaying notifications.
- Removed unnecessary fields present on notifications.
- Added additional incident title field
- Updated the notifications query to fetch the incident title from the IA node.
- Made UI changes to align with the designs for the new notification page (this will be changed when the UI changes for DPAV-1430 are done by @andrew-cunliffe)
Tested locally and is working e2e.

feat(dpav-1430): changed data structure of notifications

---

frontend/src/components/AppWrapper.tsx
frontend/src/components/Header.tsx
frontend/src/components/PageWrapper/PageWrapper.tsx
frontend/src/components/Widgets/AlertsWidget.tsx
frontend/src/components/Widgets/IntroWidget.tsx
frontend/src/components/Widgets/TaskWidget.tsx
frontend/src/components/Widgets/WidgetBase.tsx
frontend/src/components/__tests__/Widgets/AlertsWidget.test.tsx
frontend/src/pages/Home.tsx
frontend/src/pages/Incidents.tsx

- New placeholder home page for Lisa v2.
- Adds a new home page, replacing Incidents - which has been moved to /incidents
- Adds 3 widgets to the home page, displaying a short text introduction, current task statuses and notifications
- Current Tasks widget does not do anything due to Tasks work not completed yet - will be completed and wired up when available
- Alerts links to Notifications page
- Links in Tasks and Alerts widget TBC as part of design finalisation
- Tests only cover Alerts widget as others are liable to change, tests will be added to cover these when designs are finalised

feat(DPAV-1432) Placeholder home page

---

frontend/src/components/AppWrapper.tsx
frontend/src/components/Header.tsx
frontend/src/pages/MyProfile.tsx
frontend/src/pages/Settings.tsx

Adds "Manage my profile" base page to settings screen and returns display of organisational email address in profile drop-down.
Adds "Manage my profile" base page to settings screen and returns display of organisational email address in profile drop-down.
Tested locally.

feat(DPAV-1146): add further settings options and user profile base page

---

frontend/src/pages/AdminUserList.tsx
frontend/src/pages/__tests__/AdminNewUser.test.tsx
frontend/src/pages/__tests__/AdminUserList.test.tsx
frontend/src/pages/__tests__/AdminViewUser.test.tsx
frontend/src/pages/__tests__/MyProfile.test.tsx
frontend/src/pages/__tests__/Notifications.test.tsx
frontend/src/setupTests.ts

Adds tests and a styling fix for display names on the User list view.
As above.
Tested via unit tests and visual inspection.

feat(DPAV-1447): add tests and styling fix for names in user list

---

frontend/src/components/AppWrapper.tsx
frontend/src/components/IncidentPicker.tsx
frontend/src/pages/IncidentPickerPage.tsx
frontend/src/pages/Tasks.tsx

Page is needed for multiple features, needed for https://ndtp.atlassian.net/browse/DPAV-1511
See example from Tasks.tsx on how to use
via ui

feat(DPAV-1444): Add incident picker

---

deployment/sag/Dockerfile
deployment/sag/config/config.ttl
deployment/sag/docker-compose.yaml
frontend/src/components/SortFilter/SortAndFilter.tsx
frontend/src/components/SortFilter/__tests__/filter-utils.test.ts
frontend/src/components/SortFilter/filter-utils.ts
frontend/src/utils/Document/getBlobHash.ts

For the filter counts at parent level, counts how many selections have been made underneath
- Adds filter counts for nested levels in Sort & Filter component
- Fixes broken getBlobHash by making tested function more resilient to failure and including type checks

feat(DPAV-1436) Sort/Filter chip count includes nested selections

---

frontend/src/components/Widgets/TaskWidget.tsx
frontend/src/components/__tests__/Widgets/TaskWidget.test.tsx

Corrects Task widget counts to count by current user + status
As above

bugfix(DPAV-1432) Fix task counts on home page

---

frontend/src/pages/Incidents.tsx
frontend/src/pages/Tasks.tsx

Also fixed gray area at bottom of the tasks page
Update incidents page to match the designs, using the shared DataList component
Locally

feat(DPAV-1434) Update incidents page to match designs

---

frontend/src/components/AddEntity/EntityInputContainer.tsx
frontend/src/components/AddEntity/EntityOptions.tsx
frontend/src/components/AddEntity/EntityOptionsContainer.tsx

Requested changes from testing
- Form title same size as page title
- More whitespace around option containers
- Icons changed to outlined versions
Locally

feat(DPAV-1444): update styling after designer testing

---

frontend/src/components/Notifications/handlers.tsx
frontend/src/pages/IncidentTask.tsx

Noticed couple of issues when testing out the new task workflow.
- The task assigned notification was pointing at the old location.
- Was throwing an error when refreshing the page or navigating
directly to it, because of useCreateLogEntry, all other pages
use the incident id from the query params, but the task page
requires the task to be loaded first. 
Split out into a fallback component to avoid violating hook rules.
Locally

bugfix(NON-REQ): Task bug fixes

---

frontend/src/pages/Logbook.tsx

https://ndtp.atlassian.net/browse/DPAV-1440
Change add button to drop down and add the link to new task, since all the new form/update changes aren't ready yet it keeps the old link to new log entry.
Locally

feat(DPAV-1440): Add new task button from incident overview page

---

frontend/src/hooks/index.ts
frontend/src/hooks/useMenu.ts
frontend/src/pages/Home.tsx
frontend/src/pages/Logbook.tsx

https://ndtp.atlassian.net/browse/DPAV-1432
Setup the Add New button, linking to the incident picker for tasks and log entries (log entries will be replaced by update/form later).
Locally

feat(DPAV-1432): setup Add New button on summary page

---

.github/workflows/gitflow-release.yaml

Required for releases to staging, removed versioning as can be supplied by calculated env var
As above
Needs testing as part of workflow run (release to staging)

feat(NON-REQ) Add Release to Staging workflow back

---

.github/workflows/oss-checker.yml
.github/workflows/publish-github-release.yml
README.md
common/Mentionable.ts
frontend/src/components/AddEntry/Form/FormContent.tsx
frontend/src/components/lexical/EntryContent.tsx
frontend/src/components/lexical/plugins/MentionsPlugin.tsx

https://ndtp.atlassian.net/browse/DPAV-1546
The module uses a single menu key (@) for user, file, log entry, and task tagging adding the last option
Locally

feat(DPAV-1546): update tagging feature in log entries

---

frontend/src/pages/IncidentTask.tsx

Add attachment display support to task view
https://ndtp.atlassian.net/browse/DPAV-1632
Reused the AttachmentLink component in IncidentTask 
Locally

feat(DPAV-1632): Add AttachmentLinks to Task view

---

frontend/src/components/lexical/plugins/MentionsPlugin.tsx

Previously, after typing an @, and typing something beginning with either a t, l, f or u, then selecting an entity - the tagging module would throw a lexical error and break. Now it handles this by ignoring the text and just changing the trigger to the trigger of the selected entity.
For example
typing @lemons -> selecting Task -> replaces @lemons with @t: and the Task selection dropdown is shown.
As above

bugfix(NON-REQ) Fix adding terms after the @ prior to selecting entity

---

frontend/src/pages/IncidentTask.tsx

A task cannot be updated when it is in "Done" status - this change prevents any further task updates.
As above

feat(NON-REQ) Block updating a task when it is in "Done" status

---

backend/package.json
common/package.json
frontend/package.json
frontend/src/components/SortFilter/SortAndFilter.tsx
frontend/src/components/SortFilter/schemas/log-schema.ts
frontend/src/providers/__tests__/NotificationProvider.test.tsx
package-lock.json
package.json

- Modifies time picker in Sort + Filter component to be consistent with other time pickers
- S+F component on log entries now correctly filters on type "Update"
- Versions updated in package files
As above

feat(DPAV-1560, DPAV-1436) S+F Time picker consistent + Update filter

---

frontend/src/pages/IncidentTask.tsx
frontend/src/utils/Format/lexical/mention.tsx

Adds highlighting to Task description to indicate when something has been tagged. As requested, the highlighting is via making the mention bold and not rendering as a blue link. This has also been applied to mentions of users in Log Entries (since they are not interactive)
As above

feat(DPAV-1573) Highlighted tagged users in task descriptions (black + bold)

---

frontend/src/pages/Logbook.tsx

Adds active filter count to logbook sort + filter component
As above

feat(NON-REQ) Active filter count added to logbook

---

backend/src/services/fileStorage.ts
frontend/src/components/AddEntry/Form/FormContent.tsx
frontend/src/components/Recordings.tsx
frontend/src/components/__tests__/Recordings.test.tsx

Changes recordings from webm format to mp3, playable on all devices
As above

feat(NON-REQ) Change recordings from webm format to mpeg/mp3

---

common/Task.ts
frontend/src/components/OfflineBanner.tsx
frontend/src/components/Task/TaskInputContainer.tsx
frontend/src/hooks/useOfflineBootstrap.ts
frontend/src/hooks/useTasks.ts
frontend/src/offline/__tests___/dbOperations.test.ts
frontend/src/offline/__tests___/dbSync.test.ts
frontend/src/offline/db/dbOperations.ts
frontend/src/offline/db/dbSync.ts
frontend/src/offline/db/indexedDb.ts
frontend/src/offline/types/OfflineTask.ts
frontend/src/pages/IncidentTask.tsx

https://ndtp.atlassian.net/browse/DPAV-1768
Add tasks to indexdb and support for offline mode same as the other entities.
Added incidents to the offline bootstrap, so add task/update etc can still work if you went offline after loading the first page.
Locally

feat(DPAV-1768): Add support for offline task creation
