National-Digital-Twin/LISA

backend/src/services/incident.ts
frontend/src/components/AddEntry/index.tsx
frontend/src/components/EntryList/__tests__/Task.test.tsx
frontend/src/components/SetInformation/utils.ts
frontend/src/hooks/Forms/utils.ts
frontend/src/hooks/useIncidents.ts
frontend/src/utils/Form/sequence.ts
frontend/src/utils/Task/updateLogEntries.ts

Previously Change Stage log entries were being generated with a sequential number starting form #1 - this was out of step with all other log entry types which use a generated sequence number based on the current date/time.
Change Stage now uses the same Sequence generating function as all other log types
Verified locally

fix([DPAV-948]) Ensure Change Stage logs use the same Seq number as other log types

---

deployment/k8s/backend/base/istio/allow-ingress-authorization-policy.yaml

Resolves issue observed with updating task status, specifically when using dedicated tenant instances. 
Currently GET, POST and PUT operations are listed in Istio configuration. When applied to a standard dev, staging or production environment the full ingress rule is patched (https://github.com/National-Digital-Twin/LISA/blob/develop/deployment/k8s/backend/overlays/dev/patches/allow-ingress.yaml), which removes the specific verb requirements. For dedicated instances, the verbs are kept (as only the group is patched), such as at https://github.com/National-Digital-Twin/LISA/blob/develop/deployment/k8s/backend/overlays/iwc/dev/patches/allow-ingress.yaml. This being the case, when a PATCH operation is sent to update a task status, this cannot be routed properly. This adds an allow rule for …

fix(NON-REQ): allow Istio patch

---

frontend/src/components/CustomForms/FormTemplates/FormBuilder.tsx
frontend/src/components/CustomForms/FormTemplates/SortableFieldRow.tsx
frontend/src/components/CustomForms/constants.ts

DPAV-1153
- Added extra validation to stop user swapping a label field to a text field to bypass length restrictions
Tested locally and verified

bugfix(DPAV-1153) Disallow user changing label to text to bypass form label restrictions

---

frontend/src/main.tsx
frontend/src/providers/AuthContextProvider.tsx
frontend/src/utils/Map/loadLocations.ts
frontend/src/utils/auth.ts
frontend/src/utils/debounce.ts

If authentication cookie is expired, or removed a 403 is returned from all API reqs (HTML page with a window.location redirect). There is no handling for anything other than a 302 at the minute so the app continues to look like its working when all requests are failing.
https://ndtp.atlassian.net/browse/DPAV-1151
Handle 401/403 and logout the user, redirecting to the logout url.
(Also contains lint fix that prevented me committing)
Locally by returning a 403 from backend requests

bugfix(DPAV-1151): logout on query 401/403

---

frontend/src/components/NotificationsMenu/NotificationsMenu.tsx
frontend/src/components/NotificationsMenu/__tests__/NotificationsMenu.test.tsx
frontend/src/hooks/__tests__/useMessaging.test.tsx
frontend/src/hooks/useMessaging.ts

Due to overlayed useEffects in code, there is a random chance (in between frames/renders) that the fetch for Notifications will not be triggered and therefore notifications are missed by the end user unless they refresh.
This is one half of the work to make notifications work, to be paired with a polling approach for when the fetch is triggered but the notification is not yet present in the IA node.
Modified steps so that the state is only reset when the WS message has been processed, sidestepping the issue whereby the flag for a new notification is set and reset as part of the same render cycle.
Needs deploying to test fully alongside other changes to poll for notifications.

bugfix(DPAV-1148) State issue resolved with triggering notification fetch

---

backend/src/services/notifications/index.ts
developer_docs/RUN_MULTIPLE_USERS.md
frontend/src/components/NotificationsMenu/NotificationsMenu.tsx
frontend/src/hooks/useLogEntriesUpdates.tsx
frontend/src/hooks/useNotifications.ts

The notification is being sent to the user before it is saved to the IA node. This is causing an issue where the user is alerted that there is a new notification before they are able to see what it relates to.
- Added code to poll for notifications when a trigger is required to fetch them
- Added code to poll for notifications when they are marked as read
- Added optimistic updates for the call to mark the notifications as read.
- Added documentation to run multiple users for LISA locally.
- Added fix to the log entry toast appearing indefinitely when a new log entry is added.
Tested locally and is working e2e.

bugfix(dpav-1148): added polling mechanism to fetch updates to notifications

---

frontend/src/components/Form/FormGroup.tsx

There is currently no expand icon on an accordion within the log entry creation control which makes it difficult to know if the control needs to be expanded.
- Added an expand more icon to the accordion for groups in the log entry create component.
Tested locally and is working well.

bugfix(dpav-1155): added expand more icon to groups in log entry

---

frontend/src/App.tsx
frontend/src/hooks/useAuth.ts

Pre-warms the cache with Users. Currently Users are only cached when the user has hit the create log section of the site whilst online, if they don't reach that far and are knocked offline then the mentionable users are never cached.
One-off cache prewarming is done upon the site being hit, so if user is immediately knocked offline - then all features are available to them still.
Tested and verified locally that it runs once and does not fetch again upon every window refocus

feat(DPAV-1375) Pre-warm Users cache to support user tagging

---

frontend/src/components/PageTitle.tsx
frontend/src/components/Stage/StageMini.tsx
frontend/src/pages/Logbook.tsx

Redesigns Incident logbook screen per agreed designs
- Moves Incident name to title and type to subtitle
- Subtitle consists of mini-Stage chip (coloured circle) with scrollable Incident Type text and 3 dots button
- 3 dots button navigates immediately to Incident Overview page
- Add Log Entry button text modified to Add New

feat(DPAV-1436) Incident logbook screen redesign

---

Dockerfile.frontend
deployment/k8s/transparent-proxy/base/deployment.yaml
deployment/k8s/transparent-proxy/base/service.yaml
deployment/k8s/webapp/base/deployment.yaml
deployment/k8s/webapp/base/service.yaml
transparent-proxy/Dockerfile

Moves to official unprivileged NGINX image for web app and transparent proxy.
Moves to official unprivileged NGINX image for web app and transparent proxy. Also updates port bindings for routing to revised 8080 port.
To be tested in remote deployment environment.

feature(NON-REQ): convert to unprivileged NGINX image

---

backend/src/services/logEntry/utils/details/extractDetails.ts
backend/src/services/logEntry/utils/details/parseDetails.ts
backend/src/services/logEntry/utils/select/details.ts
common/LogEntryChangeDetails.ts
common/LogEntryType.ts
common/LogEntryTypes/TaskCreated.ts
common/LogEntryTypes/index.ts
frontend/src/components/EntryList/Details/TaskCreated.tsx
frontend/src/components/EntryList/Details/index.tsx
frontend/src/hooks/useTasks.ts
frontend/src/pages/CreateTask.tsx
frontend/src/utils/Task/updateLogEntries.ts

Adds a log entry when creating a task, like we do when changing the status or assignee.
https://ndtp.atlassian.net/browse/DPAV-1572
Add new TaskCreated  log entry type and handling
Locally

feat(DPAV-1572): Create log entry after task creation

---

frontend/src/pages/AdminUserList.tsx

Adds no result messaging to user search for consistency with incident and task filtering.
Adds content to user search if no results are found due to filters applied.
Tested locally (desktop) and remotely on mobile.

fix(DPAV-1447): add no result content when users not matched to filters

---

frontend/src/components/AddEntry/index.tsx
frontend/src/components/Task/TaskInputContainer.tsx
frontend/src/pages/AdminUserList.tsx
frontend/src/pages/CreateLogEntry.tsx
frontend/src/pages/IncidentTask.tsx

Users that haven't accepted the invite yet and set their name were showing up in user pickers.
Excludes inactive users (those that haven't set their name yet) from
pickers. In the future we should expose the state of a user, but this
will require larger changes to the identity api and backend to pass
this through.
Locally

bugfix(NON-REQ): exclude inactive users from selects

---

frontend/src/main.tsx
frontend/src/providers/OnlineProvider.tsx
frontend/src/utils/authRedirect.ts

Currently LISA is not recognising and reacting when a session expires, despite APIs returning a 403/401 status code.
As part of the ping workflow, as soon as a 401 or 403 is detected from an API ping, the user is immediately redirected to the login page.
Tested locally but needs deploying to test fully

fix(NON-REQ) Redirect to login after 403/401 on ping

---

frontend/src/components/InlineSelectors/BaseInlineSelector.tsx

Make inline selector dropdowns wider to facilitate thumb scrolling on mobile.
As above
A longer list still gives space around the top for the user to click off:

feat(NON-REQ) Inline selectors should be wider

---

backend/src/services/task/get.ts
frontend/src/components/AddEntry/EntryInputContainer.tsx
frontend/src/components/Incident/IncidentInputContainer.tsx
frontend/src/components/Task/TaskInputContainer.tsx
frontend/src/hooks/useTemporaryState.ts
frontend/src/setupTests.ts

https://ndtp.atlassian.net/browse/DPAV-1679
Add useTemporaryState hook to restore the entity/form back to its
original state when the back button is pressed.
Refactored EntryInputContainer to replace refresh flags and stored options
to be computed, though the confirm/cancel pattern is more complex here due
to nested hazard subforms and dynamic field dependencies.
Locally

Feature: DPAV-1295: Entity Input Confirm Button

---

frontend/src/components/AddEntry/EntryInputContainer.tsx
frontend/src/pages/CreateEntry.tsx

Sketch saving was not working
https://ndtp.atlassian.net/browse/DPAV-1441?focusedCommentId=13157
Moves canvas capturing into the input container so it can be handled before its unmounted.
Locally

bugfix(DPAV-1441): capture sketch before canvas unmount

---

frontend/src/components/Incident/IncidentInputContainer.tsx
frontend/src/components/__tests__/Incident/IncidentInputContainer.test.tsx

Edit incident also works but ‘date and time’ and ‘incident type’ still show up when they can’t actually be edited. ‘Date and time’ and ‘incident type’ should not appear when editing a form, as they can’t be edited.
https://ndtp.atlassian.net/browse/DPAV-1584?focusedCommentId=13142
Filter inputs when in edit mode
Locally, unit test

bugfix(DPAV-1584): Hide Incident type/date fields when editing

---

frontend/src/pages/CreateEntry.tsx

The date time field for a log entry was not being pre filled when the user clicked the back button and selected a new form.
- Pre filled the date time field for a log entry to now when the user clicked the back button and selected a new form.
Tested locally and is working as expected.

bugfix(dpav-1441): date time is now also prefilled when resetting a log entry

---

frontend/src/pages/CreateTask.tsx
frontend/src/pages/IncidentPickerPage.tsx

> Although it is correct, going back to a blank task form is a little odd for the flow
Added replace: true to incident picker & create task navigates so
the user will be returned to a more natural location if they hit the
back button, e.g back to /tasks rather than the create task form.
Locally

feat(NON-REQ): don't keep incident picker & task create in history

---

frontend/src/hooks/useLogEntriesUpdates.tsx

So ordering of optimistic update log entry is correct
Set dateTime to now
Locally

bugfix(DPAV-1698): Set dateTime on optimistic log entry

---

frontend/src/components/CustomForms/FormTemplates/FormBuilder.tsx
frontend/src/pages/Forms/FormTemplates.tsx

Form creation is not supported yet by the indexdb offline mode (although the mutation is queued by tanstack but won't persist refreshes), its not a requirement at the moment so disabling when offline.
Disable add/save form template buttons when offline.
Locally

feat(DPAV-1773): Disable form template creation when offline
